array_width                         = 75
attr_fn_like_width                  = 80
binop_separator                     = "Front"
blank_lines_lower_bound             = 0
blank_lines_upper_bound             = 1
brace_style                         = "PreferSameLine"
chain_width                         = 75
color                               = "Auto"
combine_control_expr                = true
comment_width                       = 80
condense_wildcard_suffixes          = true
control_brace_style                 = "AlwaysSameLine"
disable_all_formatting              = false
doc_comment_code_block_width        = 100
edition                             = "2021"
emit_mode                           = "Files"
empty_item_single_line              = true
enum_discrim_align_threshold        = 32
error_on_line_overflow              = false
error_on_unformatted                = false
fn_call_width                       = 60
fn_params_layout                    = "Compressed"
fn_single_line                      = false
force_explicit_abi                  = true
force_multiline_blocks              = false
format_code_in_doc_comments         = false
format_generated_files              = false
format_macro_bodies                 = false
format_macro_matchers               = true
format_strings                      = true
group_imports                       = "StdExternalCrate"
hard_tabs                           = false
hex_literal_case                    = "Upper"
hide_parse_errors                   = false
ignore                              = []
imports_granularity                 = "Module"
imports_indent                      = "Block"
imports_layout                      = "HorizontalVertical"
indent_style                        = "Block"
inline_attribute_width              = 0
make_backup                         = false
match_arm_blocks                    = true
match_arm_leading_pipes             = "Never"
match_block_trailing_comma          = true
max_width                           = 256
merge_derives                       = true
newline_style                       = "Auto"
normalize_comments                  = false
normalize_doc_attributes            = true
overflow_delimited_expr             = true
remove_nested_parens                = true
reorder_impl_items                  = false
reorder_imports                     = true
reorder_modules                     = true
short_array_element_width_threshold = 10
single_line_if_else_max_width       = 60
skip_children                       = false
skip_macro_invocations              = []
space_after_colon                   = true
space_before_colon                  = false
spaces_around_ranges                = false
struct_field_align_threshold        = 32
struct_lit_single_line              = true
struct_lit_width                    = 32
struct_variant_width                = 35
tab_spaces                          = 4
trailing_comma                      = "Vertical"
trailing_semicolon                  = true
type_punctuation_density            = "Wide"
unstable_features                   = true
use_field_init_shorthand            = true
use_small_heuristics                = "Default"
use_try_shorthand                   = true
version                             = "One"
where_single_line                   = true
wrap_comments                       = true
